### ISSUE TITLE
coco dataset result

### ISSUE THREAD

**Issue by jayhai** [Moreno98/GradBias#3]
I am very interested in the work of your team. I think the project you have done is excellent. However, I have encountered some issues when running your code. Could you provide the results of the COCO dataset under OpenBias detection, as well as the ranking after running GradBias? I would like to compare these results with my own. I am looking forward to your response. Thank you.

**Comment by Moreno98** [comment]
Thank you for being interested in our project.
I would be happy to help. What issues are you facing?

Please, for the OpenBias detection pipeline refer to the OpenBias [paper](https://openaccess.thecvf.com/content/CVPR2024/html/DInca_OpenBias_Open-set_Bias_Detection_in_Text-to-Image_Generative_Models_CVPR_2024_paper.html) and [code](https://github.com/Picsart-AI-Research/OpenBias).

For GradBias, as described in our paper, we used a subset (11) of the biases proposed by OpenBias. As a result, the prompts used in our study are a subset of COCO, depending on the bias under study. 
You may find these biases under `utils/config.py`. The dataset of prompts used in this work is available [here](https://drive.google.com/file/d/1nGECdt0fcwiJA-5qJgvgnZbGBp4zHnNq/view?usp=sharing). 
The results of GradBias are strictly related to the generator under study. What generator are you using? Could you provide more information about your setting and needs?

**Comment by jayhai** [comment]
I am very pleased to receive your reply. I am using the SD 1.5 generator. I am unable to log in to Hugging Face in my region, so I cannot successfully run GradBias to evaluate the generated images. I would like to know what kind of results I would get if the following command were to run successfully:
```
CUDA_VISIBLE_DEVICES=0 torchrun --nproc_per_node 1 answer_ranking_LLM.py --LLM llama3-8B --seed 0 --dataset coco
```

**Comment by Moreno98** [comment]
By running `answer_ranking_LLM.py`, you are executing the **answer ranking LLM baseline** described Sec. `4.2.2` of the paper. Please, note that this baseline does not involve image generation, as it is an image-free method leveraging the knowledge of large language models (LLMs) to estimate the influence of words on bias. Hence, this script **does not** run GradBias.
Given a prompt and bias, the output of `answer_ranking_LLM.py` gives a word ranking based on the LLM logit probabilities.
Also, this script does not require logging into Hugging Face as it uses locally downloaded weights. You can download these weights from [Llama downloads](https://www.llama.com/llama-downloads/) and by following the official Llama [Repository](https://github.com/meta-llama/llama) instructions. 
Once downloaded, please update the `utils/config.py` file with the appropriate paths to the weights.
Let me know if you have any issues running the code.

**Comment by jayhai** [comment]
Thank you very much for your answer. I downloaded the Llama-2-7b model on Meta, but when I ran it, it said there was no config.json file. I verified that the files of the downloaded model are complete, so why is this happening?

**Comment by Moreno98** [comment]
Could you be more specific? Our code does not require any `config.json` for the weights.

**Comment by jayhai** [comment]
"Do I need two GPUs to run this project? I don't have that many devices."

**Comment by Moreno98** [comment]
`Llama3-8B` or `Llama-2-7B` require 1 GPU. 
Please note that our code has not been tested with `Llama-2-7B` as we experimented with `Llama2-13B` which requires 2 GPUs. The README already provides GPU requirements for `answer_ranking_LLM.py`.

**Comment by jayhai** [comment]
Thank you very much for your answer, which has helped me solve many doubts.
